/* Autogenerated by /usr/bin/comp on Sat Nov 15 12:37:02 2014 -- do not edit */
#include "rtapi.h"
#ifdef RTAPI
#include "rtapi_app.h"
#endif
#include "rtapi_string.h"
#include "rtapi_errno.h"
#include "hal.h"

static int comp_id;

#ifdef MODULE_INFO
MODULE_INFO(linuxcnc, "component:laserfreq:Pulse driver for CO2 Laser");
MODULE_INFO(linuxcnc, "author:Ben Jackson <ben@ben.com>");
MODULE_INFO(linuxcnc, "pin:enable:bit:0:in:Enable pulse generation:0:None");
MODULE_INFO(linuxcnc, "pin:velocity:float:0:in:Velocity of the laser head (e.g. motion.current-vel):0:None");
MODULE_INFO(linuxcnc, "pin:pulse-per-unit:float:0:in:How many pulses per unit distance:0:None");
MODULE_INFO(linuxcnc, "pin:pulse:bit:0:out:Output firing pulse:None:None");
MODULE_INFO(linuxcnc, "pin:continuous:bit:0:out:True if current inputs are causing continuous (not pulsed) output:None:None");
MODULE_INFO(linuxcnc, "param:duration:s32:0:rw:Duration of each pulse in ns:None:None");
MODULE_INFO(linuxcnc, "funct:make_pulses:0:Add to fast thread to make laser pulses");
MODULE_INFO(linuxcnc, "funct:update:1:Add to update thread to compute pulse parameters");
MODULE_INFO(linuxcnc, "param:interval:s32:0:r::None:None");
MODULE_INFO(linuxcnc, "param:accum:s32:0:r::None:None");
MODULE_INFO(linuxcnc, "param:pulse_remain:s32:0:r::None:None");
MODULE_INFO(linuxcnc, "license:GPL");
MODULE_LICENSE("GPL");
#endif // MODULE_INFO


struct __comp_state {
    struct __comp_state *_next;
    hal_bit_t *enable;
    hal_float_t *velocity;
    hal_float_t *pulse_per_unit;
    hal_bit_t *pulse;
    hal_bit_t *continuous;
    hal_s32_t duration;
    hal_s32_t interval;
    hal_s32_t accum;
    hal_s32_t pulse_remain;
    int updated;

};
struct __comp_state *__comp_inst=0;
struct __comp_state *__comp_first_inst=0, *__comp_last_inst=0;

static void make_pulses(struct __comp_state *__comp_inst, long period);
static void update(struct __comp_state *__comp_inst, long period);
static int __comp_get_data_size(void);
#undef TRUE
#define TRUE (1)
#undef FALSE
#define FALSE (0)
#undef true
#define true (1)
#undef false
#define false (0)

static int export(char *prefix, long extra_arg) {
    char buf[HAL_NAME_LEN + 1];
    int r = 0;
    int sz = sizeof(struct __comp_state) + __comp_get_data_size();
    struct __comp_state *inst = hal_malloc(sz);
    memset(inst, 0, sz);
    r = hal_pin_bit_newf(HAL_IN, &(inst->enable), comp_id,
        "%s.enable", prefix);
    if(r != 0) return r;
    *(inst->enable) = 0;
    r = hal_pin_float_newf(HAL_IN, &(inst->velocity), comp_id,
        "%s.velocity", prefix);
    if(r != 0) return r;
    *(inst->velocity) = 0;
    r = hal_pin_float_newf(HAL_IN, &(inst->pulse_per_unit), comp_id,
        "%s.pulse-per-unit", prefix);
    if(r != 0) return r;
    *(inst->pulse_per_unit) = 0;
    r = hal_pin_bit_newf(HAL_OUT, &(inst->pulse), comp_id,
        "%s.pulse", prefix);
    if(r != 0) return r;
    r = hal_pin_bit_newf(HAL_OUT, &(inst->continuous), comp_id,
        "%s.continuous", prefix);
    if(r != 0) return r;
    r = hal_param_s32_newf(HAL_RW, &(inst->duration), comp_id,
        "%s.duration", prefix);
    if(r != 0) return r;
    r = hal_param_s32_newf(HAL_RO, &(inst->interval), comp_id,
        "%s.interval", prefix);
    if(r != 0) return r;
    r = hal_param_s32_newf(HAL_RO, &(inst->accum), comp_id,
        "%s.accum", prefix);
    if(r != 0) return r;
    r = hal_param_s32_newf(HAL_RO, &(inst->pulse_remain), comp_id,
        "%s.pulse-remain", prefix);
    if(r != 0) return r;
    rtapi_snprintf(buf, sizeof(buf), "%s.make-pulses", prefix);
    r = hal_export_funct(buf, (void(*)(void *inst, long))make_pulses, inst, 0, 0, comp_id);
    if(r != 0) return r;
    rtapi_snprintf(buf, sizeof(buf), "%s.update", prefix);
    r = hal_export_funct(buf, (void(*)(void *inst, long))update, inst, 1, 0, comp_id);
    if(r != 0) return r;
    if(__comp_last_inst) __comp_last_inst->_next = inst;
    __comp_last_inst = inst;
    if(!__comp_first_inst) __comp_first_inst = inst;
    return 0;
}
static int default_count=1, count=0;
char *names[16] = {0,};
RTAPI_MP_INT(count, "number of laserfreq");
RTAPI_MP_ARRAY_STRING(names, 16, "names of laserfreq");
int rtapi_app_main(void) {
    int r = 0;
    int i;
    comp_id = hal_init("laserfreq");
    if(comp_id < 0) return comp_id;
    if(count && names[0]) {
        rtapi_print_msg(RTAPI_MSG_ERR,"count= and names= are mutually exclusive\n");
        return -EINVAL;
    }
    if(!count && !names[0]) count = default_count;
    if(count) {
        for(i=0; i<count; i++) {
            char buf[HAL_NAME_LEN + 1];
            rtapi_snprintf(buf, sizeof(buf), "laserfreq.%d", i);
        r = export(buf, i);
            if(r != 0) break;
       }
    } else {
        for(i=0; names[i]; i++) {
        r = export(names[i], i);
            if(r != 0) break;
       }
    }
    if(r) {
        hal_exit(comp_id);
    } else {
        hal_ready(comp_id);
    }
    return r;
}

void rtapi_app_exit(void) {
    hal_exit(comp_id);
}

#undef FUNCTION
#define FUNCTION(name) static void name(struct __comp_state *__comp_inst, long period)
#undef EXTRA_SETUP
#define EXTRA_SETUP() static int extra_setup(struct __comp_state *__comp_inst, char *prefix, long extra_arg)
#undef EXTRA_CLEANUP
#define EXTRA_CLEANUP() static void extra_cleanup(void)
#undef fperiod
#define fperiod (period * 1e-9)
#undef enable
#define enable (0+*__comp_inst->enable)
#undef velocity
#define velocity (0+*__comp_inst->velocity)
#undef pulse_per_unit
#define pulse_per_unit (0+*__comp_inst->pulse_per_unit)
#undef pulse
#define pulse (*__comp_inst->pulse)
#undef continuous
#define continuous (*__comp_inst->continuous)
#undef duration
#define duration (__comp_inst->duration)
#undef interval
#define interval (__comp_inst->interval)
#undef accum
#define accum (__comp_inst->accum)
#undef pulse_remain
#define pulse_remain (__comp_inst->pulse_remain)
#undef updated
#define updated (__comp_inst->updated)


#line 19 "laserfreq.comp"

FUNCTION(update) {

    if (velocity == 0.0 || pulse_per_unit == 0) {
        updated = 0;
    } else {
        if ( pulse_per_unit < 0.0 ) {
            // duty cycle is just a function of % and duration
            interval = duration * -100.0 / pulse_per_unit;
        } else {
            // velocity * pulse-per-unit gives pulses per second
            // pulse interval is then 1/pps 
            interval = 1000000000.0 / (velocity * pulse_per_unit);
        }
        updated = 1;
    }
}

FUNCTION(make_pulses) {
    if (!enable || !updated) {
        accum = 0;
        pulse_remain = 0;
        pulse = 0;
        continuous = 0;
        return;
    }

    accum += period;
    if (accum > interval) {
        accum -= interval;
        if (accum > interval)
            accum = 0;
        continuous = (pulse_remain > 0);
        pulse_remain = duration;
    }

    if (pulse_remain > 0) {
        pulse = 1;
        pulse_remain -= period;
    } else {
        pulse = 0;
    }
}

static int __comp_get_data_size(void) { return 0; }
